// 記事カテゴリの単一ソース（category-index と /sitemap/ で共用）
export type CategoryArticle = { href: string; title: string };

export type Category = {
  id: string;
  name: string;
  color: string;
  desc: string;
  articles: CategoryArticle[];
};

export const categories: Category[] = [
  {
    id: "start",
    name: "はじめての方へ",
    color: "#7c3a55",
    desc: "転職活動の全体像をつかむための入門記事です。未経験からのロードマップ、エージェントの選び方、活動期間の目安など、最初に読むと後の記事が理解しやすくなります。",
    articles: [
      { href: "/articles/beginner/", title: "未経験から女性エンジニアになるには？現実のロードマップ" },
      { href: "/articles/how-to-choose/", title: "転職エージェントの選び方｜7つのチェックポイント" },
      { href: "/articles/schedule/", title: "転職活動のスケジュールと期間の目安" },
      { href: "/articles/demand/", title: "女性エンジニアの需要と将来性" },
      { href: "/articles/programming-school/", title: "プログラミングスクールの選び方と給付金活用" },
      { href: "/articles/faq-all/", title: "女性エンジニア転職のFAQ総まとめ" },
    ],
  },
  {
    id: "shokushu",
    name: "職種を知る",
    color: "#7c3a55",
    desc: "エンジニアと一口に言っても職種ごとに仕事内容・年収・未経験ハードルは大きく異なります。開発系からデータ・セキュリティ・マネジメント・デザイン系まで17職種を解説しています。",
    articles: [
      { href: "/articles/frontend/", title: "フロントエンドエンジニア転職ガイド" },
      { href: "/articles/backend/", title: "バックエンドエンジニア転職ガイド" },
      { href: "/articles/infrastructure/", title: "インフラエンジニア転職ガイド" },
      { href: "/articles/mobile-app/", title: "モバイルアプリエンジニア転職ガイド" },
      { href: "/articles/data-scientist/", title: "データサイエンティスト転職ガイド" },
      { href: "/articles/data-engineer/", title: "データエンジニア転職ガイド" },
      { href: "/articles/ai-ml-career/", title: "AI・機械学習エンジニア転職ガイド" },
      { href: "/articles/security/", title: "セキュリティエンジニア転職ガイド" },
      { href: "/articles/sre-devops/", title: "SRE・DevOpsエンジニア転職ガイド" },
      { href: "/articles/embedded/", title: "組み込み・IoTエンジニア転職ガイド" },
      { href: "/articles/qa-tester/", title: "QAエンジニア・テスター転職ガイド" },
      { href: "/articles/internal-se/", title: "社内SE転職ガイド" },
      { href: "/articles/it-consultant/", title: "ITコンサルタント転職ガイド" },
      { href: "/articles/support-engineer/", title: "テクニカルサポート・カスタマーサクセス転職ガイド" },
      { href: "/articles/pm-director/", title: "PM・Webディレクター転職ガイド" },
      { href: "/articles/web-designer/", title: "Webデザイナーからエンジニアへのキャリアチェンジ" },
      { href: "/articles/ux-designer/", title: "UXデザイナー転職ガイド" },
    ],
  },
  {
    id: "skill",
    name: "言語・スキルから選ぶ",
    color: "#c15f47",
    desc: "学ぶ言語・スキルで目指せる職種と年収レンジが変わります。主要8言語に加えて、クラウド（AWS・GCP・Azure）やデータベースのスキル軸でも転職戦略を解説しています。",
    articles: [
      { href: "/articles/javascript-career/", title: "JavaScriptで転職する" },
      { href: "/articles/typescript-react/", title: "TypeScript・Reactエンジニア転職" },
      { href: "/articles/python-career/", title: "Pythonで転職する" },
      { href: "/articles/java-career/", title: "Javaエンジニア転職" },
      { href: "/articles/ruby-career/", title: "Rubyエンジニア転職" },
      { href: "/articles/php-career/", title: "PHPエンジニア転職" },
      { href: "/articles/go-career/", title: "Goエンジニア転職" },
      { href: "/articles/csharp-career/", title: "C#エンジニア転職" },
      { href: "/articles/aws-career/", title: "AWSエンジニア転職" },
      { href: "/articles/cloud-gcp-azure/", title: "クラウドエンジニア転職（GCP・Azure）" },
      { href: "/articles/sql-database/", title: "データベースエンジニア（DBA）転職" },
    ],
  },
  {
    id: "cert",
    name: "資格",
    color: "#10b981",
    desc: "資格は転職の必須条件ではありませんが、未経験者の学習証明やキャリアアップの武器になります。まず資格マップで全体像を確認し、目的に合う個別資格の記事へ進んでください。",
    articles: [
      { href: "/articles/certification/", title: "資格ガイド｜目的別おすすめ資格マップ" },
      { href: "/articles/cert-itpassport/", title: "ITパスポート試験ガイド" },
      { href: "/articles/cert-kihonjoho/", title: "基本情報技術者試験ガイド" },
      { href: "/articles/cert-oyojoho/", title: "応用情報技術者試験ガイド" },
      { href: "/articles/cert-aws/", title: "AWS認定資格ガイド" },
      { href: "/articles/cert-lpic/", title: "LPIC・LinuC資格ガイド" },
      { href: "/articles/cert-python/", title: "Python資格ガイド" },
      { href: "/articles/cert-database/", title: "データベース資格ガイド" },
    ],
  },
  {
    id: "salary",
    name: "年収",
    color: "#7c3a55",
    desc: "公的統計・公開調査に基づく年収の実データを、年代別・職種別・言語別の3つの切り口で整理しています。年収1000万への道筋と、転職時に重要な年収交渉の実践方法もこちらです。",
    articles: [
      { href: "/articles/salary/", title: "女性エンジニアの年収はいくら？実データと年収アップ術" },
      { href: "/articles/salary-by-age/", title: "年代別年収【20代〜50代】" },
      { href: "/articles/salary-by-job/", title: "職種別年収比較" },
      { href: "/articles/salary-by-language/", title: "言語別年収比較" },
      { href: "/articles/salary-1000man/", title: "年収1000万を目指す方法" },
      { href: "/articles/negotiation/", title: "年収交渉術｜タイミングと伝え方" },
    ],
  },
  {
    id: "hatarakikata",
    name: "働き方",
    color: "#7c3a55",
    desc: "リモートワーク・時短・週3〜4日勤務・副業・フリーランス・派遣など、雇用形態と働き方の選択肢を比較できます。フルリモート企業の見極め方や契約社員からの正社員化もこちらです。",
    articles: [
      { href: "/articles/remote-jobs/", title: "在宅・リモート転職ガイド" },
      { href: "/articles/fullremote-companies/", title: "フルリモート企業の見極め方" },
      { href: "/articles/short-time/", title: "時短勤務で転職・継続するガイド" },
      { href: "/articles/short-week/", title: "週3・週4・時短で働ける求人の探し方" },
      { href: "/articles/work-life-balance/", title: "ワークライフバランスの実態データ" },
      { href: "/articles/side-job/", title: "副業の始め方と単価相場" },
      { href: "/articles/freelance/", title: "フリーランスエンジニアの始め方" },
      { href: "/articles/dispatch/", title: "派遣エンジニアという働き方" },
      { href: "/articles/contract-to-perm/", title: "契約社員から正社員を目指す" },
    ],
  },
  {
    id: "ryoritsu",
    name: "両立・ライフイベント",
    color: "#c15f47",
    desc: "出産・育児とエンジニアキャリアの両立をテーマにした記事群です。育休取得率の実データ、復職ロードマップ、育休中のリスキリング、両立家庭のリアルな1日まで網羅しています。",
    articles: [
      { href: "/articles/mama-engineer/", title: "ママエンジニアの働き方ガイド" },
      { href: "/articles/after-maternity/", title: "産休・育休後の転職｜復帰と転職の判断基準" },
      { href: "/articles/maternity-leave-rate/", title: "IT業界の育休取得率・復帰率データ" },
      { href: "/articles/career-lifeevent-timing/", title: "転職と妊娠・出産のタイミング設計｜制度上の分岐点" },
      { href: "/articles/maternity-money-guide/", title: "産休・育休・時短のお金ガイド｜給付金の計算基礎" },
      { href: "/articles/return-to-work/", title: "ブランクからの復職ロードマップ" },
      { href: "/articles/work-childcare-day/", title: "育児と両立する1日のタイムスケジュール" },
      { href: "/articles/reskilling-leave/", title: "育休中のスキルアップ・リスキリング" },
    ],
  },
  {
    id: "nendai",
    name: "年代別",
    color: "#10b981",
    desc: "20代のポテンシャル採用、30代の両立とキャリアアップ、40代の経験の活かし方。年代によって転職市場での評価軸は変わります。自分の年代のガイドから読み始めるのが近道です。",
    articles: [
      { href: "/articles/age-20s/", title: "20代女性エンジニアの転職ガイド" },
      { href: "/articles/age-30s/", title: "30代女性エンジニアの転職ガイド" },
      { href: "/articles/age-40s/", title: "40代女性エンジニアの転職ガイド" },
    ],
  },
  {
    id: "chiiki",
    name: "地域から探す",
    color: "#7c3a55",
    desc: "東京・大阪・名古屋・福岡の求人動向と年収相場に加え、地方在住×フルリモートという選択肢も解説。東京都の女性ITエンジニア育成事業（公的支援）の記事もこちらです。",
    articles: [
      { href: "/articles/tokyo/", title: "東京の転職ガイド" },
      { href: "/articles/tokyo-women-training/", title: "東京都の女性ITエンジニア育成事業とは" },
      { href: "/articles/osaka/", title: "大阪・関西の転職ガイド" },
      { href: "/articles/nagoya/", title: "名古屋・東海の転職ガイド" },
      { href: "/articles/fukuoka/", title: "福岡の転職ガイド" },
      { href: "/articles/regional-remote/", title: "地方在住×フルリモートで転職する" },
    ],
  },
  {
    id: "senko",
    name: "選考対策",
    color: "#7c3a55",
    desc: "書類作成から面接・コーディングテスト・オファー面談・退職交渉まで、選考プロセスを時系列でカバーしています。在職中の活動の進め方と円満退職の記事も含みます。",
    articles: [
      { href: "/articles/resume-guide/", title: "職務経歴書・スキルシートの書き方" },
      { href: "/articles/portfolio/", title: "ポートフォリオ作成ガイド" },
      { href: "/articles/casual-interview/", title: "カジュアル面談の対策" },
      { href: "/articles/interview-guide/", title: "転職面接対策｜流れと頻出質問" },
      { href: "/articles/technical-interview/", title: "技術面接の対策" },
      { href: "/articles/coding-test/", title: "コーディングテスト対策" },
      { href: "/articles/reverse-questions/", title: "面接の逆質問 例文集" },
      { href: "/articles/offer-meeting/", title: "オファー面談で確認すべきこと" },
      { href: "/articles/company-check-guide/", title: "女性が働きやすいIT企業の見極め方・実務編" },
      { href: "/articles/job-hunting-while-employed/", title: "在職中の転職活動の進め方" },
      { href: "/articles/amicable-resignation/", title: "円満退職・退職交渉の進め方" },
    ],
  },
  {
    id: "gyokai",
    name: "業界研究",
    color: "#c15f47",
    desc: "同じエンジニアでも、Web系・SIer・ゲーム業界・スタートアップでは文化も年収もキャリアパスも異なります。SESと自社開発の違いはキャリアへの影響が大きいので要チェックです。",
    articles: [
      { href: "/articles/web-industry/", title: "Web業界で働くリアル" },
      { href: "/articles/sier-industry/", title: "SIerで働くリアル" },
      { href: "/articles/game-industry/", title: "ゲーム業界で働くリアル" },
      { href: "/articles/startup/", title: "スタートアップ転職の魅力とリスク" },
      { href: "/articles/ses-vs-jisha/", title: "SESと自社開発の違いと見極め方" },
    ],
  },
  {
    id: "kouteki",
    name: "公的支援・給付金で学ぶ",
    color: "#c15f47",
    desc: "受講料無料の訓練や給付金など、国・自治体の制度を使ってITスキルを身につける方法です。東京都の女性ITエンジニア育成事業（「地域から探す」に掲載）とあわせてご覧ください。",
    articles: [
      { href: "/articles/women-it-support-map/", title: "全国の女性向けIT訓練・支援まとめ【公的制度ハブ】" },
      { href: "/articles/women-digital-college/", title: "東京都 女性デジタルカレッジとは（無料・託児つき）" },
      { href: "/articles/training-benefit-it/", title: "教育訓練給付制度でITスキルを学ぶ（最大80%給付）" },
      { href: "/articles/hello-training-it/", title: "求職者支援訓練（ハロートレーニング）でITを学ぶ" },
      { href: "/articles/manabi-dx/", title: "マナビDX（経産省）の無料講座活用ガイド" },
      { href: "/articles/saitama-women-training/", title: "埼玉県 女性のデジタル人材育成推進事業の解説（無料・在職中も可）" },
      { href: "/articles/hitorioya-it-training/", title: "ひとり親のIT資格取得に使える給付金（高等職業訓練促進給付金）" },
      { href: "/articles/iwate-women-digital/", title: "岩手県 いわて女性デジタル人材育成プロジェクト" },
      { href: "/articles/yamaguchi-women-digital/", title: "山口県 WINGs YAMAGUCHI（女性デジタル人材育成）" },
      { href: "/articles/kanagawa-women-digital/", title: "神奈川県 女性のためのデジタルスキル育成講座" },
      { href: "/articles/yamanashi-women-digital/", title: "山梨県 やまなし女性デジタル人材プロジェクト" },
      { href: "/articles/fukuoka-digital-woman/", title: "福岡県 でじたる女子プロジェクト（事業終了・経緯解説）" },
      { href: "/articles/training-not-selected/", title: "女性IT育成事業に落ちたら？代替ルートと研修付き転職" },
      { href: "/articles/training-after-graduation/", title: "女性IT育成事業の修了後の転職活動ガイド" },
      { href: "/articles/learn-vs-transfer/", title: "先に学ぶ vs 転職して実務で学ぶ｜ルート比較" },
      { href: "/articles/women-digital-plan/", title: "新・女性デジタル人材育成プランとは（個人が使える支援への入口）" },
    ],
  },
  {
    id: "hikaku",
    name: "エージェント・サービス比較",
    color: "#10b981",
    desc: "転職エージェントと転職サイトの違い、特化型と総合型の使い分けから、主要サービス同士の具体的な比較まで。公式公開値に基づいて違いを整理しています。",
    articles: [
      { href: "/articles/agent-vs-site/", title: "転職エージェントと転職サイトの違い" },
      { href: "/articles/specialized-vs-general/", title: "IT特化型と総合型の使い分け" },
      { href: "/articles/levtech-vs-geekly/", title: "レバテックキャリアとGeeklyの違い" },
      { href: "/articles/type-vs-doda/", title: "type女性の転職エージェントとdodaの違い" },
      { href: "/articles/workport-vs-recruit/", title: "ワークポートとリクルートエージェントの違い" },
      { href: "/articles/green-vs-reworks/", title: "GreenとReWorksの違い" },
      { href: "/articles/techgo-career-mendan/", title: "テックゴーの無料キャリア面談とは" },
      { href: "/articles/techgo-vs-levtech/", title: "テックゴーとレバテックキャリアの違い" },
    ],
  },
  {
    id: "career",
    name: "キャリア・職場環境",
    color: "#7c3a55",
    desc: "5年後・10年後を見据えたキャリア設計と、長く働き続けるための職場環境の見極め方。管理職への道、働きやすい企業の選び方、ハラスメント対処、海外転職までカバーしています。",
    articles: [
      { href: "/articles/career-path/", title: "キャリアパス完全マップ｜5つの方向性" },
      { href: "/articles/women-manager/", title: "管理職・マネージャーを目指すガイド" },
      { href: "/articles/long-career-tips/", title: "長く働き続けるコツ" },
      { href: "/articles/women-friendly-companies/", title: "女性が働きやすいIT企業の見極め方" },
      { href: "/articles/harassment/", title: "職場のハラスメント対処ガイド" },
      { href: "/articles/success-stories/", title: "転職成功パターン分析" },
      { href: "/articles/community/", title: "コミュニティ・勉強会一覧" },
      { href: "/articles/work-abroad/", title: "海外転職ガイド" },
    ],
  },
];

